import {
  Boxes,
  Camera,
  CameraIcon,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleMinus,
  CircleHelp,
  Copy,
  CopyPlus,
  Eye,
  EyeOff,
  Focus,
  Info,
  Keyboard,
  Layers3,
  Library,
  ListTree,
  LocateFixed,
  Lock,
  MoreHorizontal,
  Package,
  PackageMinus,
  PackagePlus,
  Pencil,
  Pin,
  PinOff,
  Plus,
  Plug,
  RefreshCw,
  Redo2,
  Ruler,
  Save,
  Search,
  SlidersHorizontal,
  SquarePen,
  Star,
  Tag,
  TextCursorInput,
  Trash2,
  Ungroup,
  Unlock,
  Undo2,
  Upload,
  X,
  type LucideIcon
} from "lucide-react";

export const WORKBENCH_ICON_IDS = [
  "save",
  "undo",
  "redo",
  "duplicate",
  "delete",
  "measurement",
  "labels",
  "connection-points",
  "viewpoints",
  "rename",
  "selection-tools",
  "help",
  "keyboard",
  "info",
  "search",
  "more",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevron-down",
  "asset",
  "favorite",
  "add",
  "filter",
  "library",
  "explorer",
  "layers",
  "groups",
  "create",
  "remove",
  "custom-variant",
  "edit",
  "ungroup",
  "show",
  "hide",
  "lock",
  "unlock",
  "isolate",
  "capture",
  "apply",
  "update",
  "previous",
  "next",
  "expand",
  "collapse",
  "reset",
  "clear",
  "close",
  "import",
  "add-members",
  "remove-members",
  "edit-assembly",
  "finish-edit",
  "rename-text",
  "pin",
  "unpin"
] as const;

export type WorkbenchIconId = typeof WORKBENCH_ICON_IDS[number];

const iconById = Object.freeze({
  save: Save,
  undo: Undo2,
  redo: Redo2,
  duplicate: Copy,
  delete: Trash2,
  measurement: Ruler,
  labels: Tag,
  "connection-points": Plug,
  viewpoints: Camera,
  rename: Pencil,
  "selection-tools": SlidersHorizontal,
  help: CircleHelp,
  keyboard: Keyboard,
  info: Info,
  search: Search,
  more: MoreHorizontal,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  asset: Package,
  favorite: Star,
  add: Plus,
  filter: SlidersHorizontal,
  library: Library,
  explorer: ListTree,
  layers: Layers3,
  groups: Boxes,
  create: Plus,
  remove: CircleMinus,
  "custom-variant": CopyPlus,
  edit: Pencil,
  ungroup: Ungroup,
  show: Eye,
  hide: EyeOff,
  lock: Lock,
  unlock: Unlock,
  isolate: Focus,
  capture: CameraIcon,
  apply: LocateFixed,
  update: RefreshCw,
  previous: ChevronLeft,
  next: ChevronRight,
  expand: ChevronRight,
  collapse: ChevronDown,
  reset: RefreshCw,
  clear: X,
  close: X,
  import: Upload,
  "add-members": PackagePlus,
  "remove-members": PackageMinus,
  "edit-assembly": SquarePen,
  "finish-edit": Check,
  "rename-text": TextCursorInput,
  pin: Pin,
  unpin: PinOff
} satisfies Record<WorkbenchIconId, LucideIcon>);

export const isWorkbenchIconId = (iconId: string): iconId is WorkbenchIconId =>
  Object.prototype.hasOwnProperty.call(iconById, iconId);

export const getWorkbenchIcon = (iconId: string): LucideIcon | undefined =>
  isWorkbenchIconId(iconId) ? iconById[iconId] : undefined;

export const WorkbenchIcon = ({ iconId }: { iconId: string }) => {
  const Icon = getWorkbenchIcon(iconId);
  return Icon ? <Icon aria-hidden="true" focusable="false" /> : null;
};
